### ISSUE TITLE
Update refresh_state to also circle through _state_refresh_input_pairings

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#102]
At the moment the function `refresh_state()` automatically iterats through the list `_state_refresh_output_pairings`.

Even that the list `_state_refresh_input_pairings` is defined and all supporing functions like `get_input_by_pairing()`, `_refresh_state_from_input()` and `_refresh_state_from_inputs()` are defined, this part is currently not used.

Please make it "feature-complete". There is no DeviceClass currently implemented, which uses this feature, but it also shouldn't affect it from a performance point-of-view as it is empty and so nothing happens.

**Comment by kingsleyadam** [comment]
All devices states should come from the outputs, I was actually debating removing any of the state related functions for inputs as inputs should only be used for send commands to the device functions.

Also, writing tests for code that'll never be used will be impossible.

**Comment by derjoerg** [comment]
> All devices states should come from the outputs, I was actually debating removing any of the state related functions for inputs as inputs should only be used for send commands to the device functions.

OK, fully understand. So I would vote for removing the "inputs" part completely. If really something should come up in the future, which might make this necessary, we can re-think again.

> 
> Also, writing tests for code that'll never be used will be impossible.

Agree
