### ISSUE TITLE
Cleanup CoverActuator

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#116]
The current implementation of `CoverActuator` holds the following functions:
```
    def is_cover_closed(self):
        """Helper-Function returns true if the cover is closed."""
        return self.position == 100

    def is_cover_opening(self):
        """Helper-Function returns true if the cover is opening."""
        return self.state == 2

    def is_cover_closing(self):
        """Helper-Function returns true if the cover is closing."""
        return self.state == 3
```
These functions were only implemented to act as helper-functions for the HA-integration. As these functions have nothing to do with F@H they should be removed from the pypi package and completely implemented in HA.

**Comment by kingsleyadam** [comment]
How would you implement these in Home Assistant?

I think there's definitely a benefit to keeping them here. They're not necessarily specific to Home Assistant as these are common functions in smart homes.

**Comment by derjoerg** [comment]
> How would you implement these in Home Assistant?

Looking at `is_closing`
In HA, in the cover entity I need to define a a property for `is_closing` and instead of just calling `return self._cover.is_cover_closing()`, I would just call `return self._cover.state == 3`.

> 
> I think there's definitely a benefit to keeping them here. They're not necessarily specific to Home Assistant as these are common functions in smart homes.

If you are against it, I can keep them in, I just don't see the benefit in them

**Comment by kingsleyadam** [comment]
I think removing is ok as long as the state information is useful. Home Assistant shouldn't have to know that `state == 3`  means `is_closing`.

So I'd replace the state value with another enum of possible state options.

Then Home Assistant could do `self._cover.state == closing`.

**Comment by derjoerg** [comment]
> I think removing is ok as long as the state information is useful. Home Assistant shouldn't have to know that `state == 3` means `is_closing`.
> 
> So I'd replace the state value with another enum of possible state options.
> 
> Then Home Assistant could do `self._cover.state == closing`.

I'll try it

**Comment by kingsleyadam** [comment]
Not sure when you plan on making this change, but I can hold off on https://github.com/kingsleyadam/local-abbfreeathome/pull/117 until then.

**Comment by derjoerg** [comment]
This would be really great.
I plan this for today to get everything ready to finally implememt the cover-entity in HA.
