### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#13]
Hi,

I just wanted to start to test your new package and have encountered the following:
- Your first example (Get Configuration) is working as expected and I get a lot of output
- Your second (Get Devices) and third (WebSocket) example always returns the following error message:
```
(.venv) joerg@iot-server:~/freeathome$ python3.12 test3.py 
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/joerg/freeathome/test3.py", line 22, in <module>
    asyncio.run(_free_at_home.load_devices())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/joerg/freeathome/.venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 94, in load_devices
    await self._load_switches()
  File "/home/joerg/freeathome/.venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 97, in _load_switches
    _switch_devices = await self.get_devices_by_function(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/freeathome/.venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 52, in get_devices_by_function
    "room_name": await self.get_room_name(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/freeathome/.venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 81, in get_room_name
    .get("name", "unknown")
     ^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

And for sure, I have several devices with FunctionID=7

**Comment by kingsleyadam** [comment]
I'll take a look, what's most likely happening is the device isn't in a room. I've set a default room for this scenario but the code obviously isn't using it.

**Comment by derjoerg** [comment]
Yep,

I also just checked the code and my setup and I have one switch-channel in an device, which is not associated to a room (and so you can leave these out as only channels, which are associated to a room can be controlled in F@H)

**Comment by derjoerg** [comment]
This works, but it returns the unassigned channel.
This might be ok for this library but for the HA-integration such channels need to be omitted.
Perhaps by adding an optional parameter to "load_devices" (which will be passed to "_load_switches")? e.g. something like "omitUnassociated" which defaults to false and returns everything and especially the HA-integration sets this parameter to "true"

**Comment by kingsleyadam** [comment]
What would be the issue with including unassociated channels into Home Assistant? Just curious if this would actually be problematic, or just a possible inconvenience? We don't have to use all entities added to HA, but it would give other users the ability to use a channel even if it's not associated with a floor plan.

**Comment by derjoerg** [comment]
I'm absolutely with you that it wouldn't harm anybody if these channels are also added to HA.
I was just under the impression, as such channels are not useable in the F@H app, they are also not useable through the API and so are totally useless in HA. But this is only my impression, I never tested it.

**Comment by kingsleyadam** [comment]
> I'm absolutely with you that it wouldn't harm anybody if these channels are also added to HA. I was just under the impression, as such channels are not useable in the F@H app, they are also not useable through the API and so are totally useless in HA. But this is only my impression, I never tested it.

@derjoerg , Do you mind sharing the device config that triggered this for you? Anything with the `FID_SWITCH_ACTUATOR` function should be a usable/switchable device.

Unless maybe it's using a different interface I haven't seen before. That's one thing I do need to add, the ability to filter devices by interface so we don't get things like Philips Hue devices in Home Assistant.

I wish ABB would publish a list of known possible interfaces.

**Comment by kingsleyadam** [comment]
Also a heads up @derjoerg, I did merge this into the `main` branch and I've updated the Home Assistant Integration to include this fix in case you wanted to test how the integration would pull the devices into HA. https://github.com/kingsleyadam/local-abbfreeathome-hass/releases/tag/0.4.1

**Comment by derjoerg** [comment]
> > I'm absolutely with you that it wouldn't harm anybody if these channels are also added to HA. I was just under the impression, as such channels are not useable in the F@H app, they are also not useable through the API and so are totally useless in HA. But this is only my impression, I never tested it.
> 
> @derjoerg , Do you mind sharing the device config that triggered this for you? Anything with the `FID_SWITCH_ACTUATOR` function should be a usable/switchable device.
> 
> Unless maybe it's using a different interface I haven't seen before. That's one thing I do need to add, the ability to filter devices by interface so we don't get things like Philips Hue devices in Home Assistant.
> 
> I wish ABB would publish a list of known possible interfaces.

I just checked the new HA-integration and even that a channel isn't useable within the F@H-app I can control it through HA and API, so all good to have it included in HA

**Comment by derjoerg** [comment]
> Also a heads up @derjoerg, I did merge this into the `main` branch and I've updated the Home Assistant Integration to include this fix in case you wanted to test how the integration would pull the devices into HA. https://github.com/kingsleyadam/local-abbfreeathome-hass/releases/tag/0.4.1

Works like a charme.

Do you might think it is meaningful to open "Discussions" here and for your HA-integration? Or should all questions and/or discussions open as issues?

**Comment by kingsleyadam** [comment]
Good idea, I’ve enabled discussions on the repository.
