### ISSUE TITLE
Use another source for functionIds, pairingIds and perhaps parameterIds

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#15]
Hi,
I saw in the source-code that you used the official developer documentation for getting the functionIds and pairingIds.
I found out that - for whatever reason - ABB don't update this documentation for a long time. Sure, for now these Ids are more than enough but perhaps it is meaningful to use a more accurate list to be future-proof...

The following source has much more up-to-date information:
functionIds: https://github.com/Busch-Jaeger/node-free-at-home/blob/master/src/functionIds.ts
pairingIds: https://github.com/Busch-Jaeger/node-free-at-home/blob/master/src/pairingIds.ts
parameterIds: https://github.com/Busch-Jaeger/node-free-at-home/blob/master/src/parameterIds.ts

Just a suggestion

**Comment by kingsleyadam** [comment]
Good one, I’m not too thrilled with the function value look-ups either. I’ll look into this.
