### ISSUE TITLE
Ignore channels with a functionID of ""

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#27]
Hi,

I just ran into the problem, that the function "get_devices_by_function" requires that the functionID is set AND is a number.

I have a "SmartTouch 10" device and - don't ask me why - this device has several channels with a functionID = "". They have a displayName of e.g. "1,1,1" or "Programmable button 1".

To circumvent this I added the following below line 39:
```
if _channel.get("functionID", -1) == -1 or len(_channel.get("functionID")) == 0:
    continue
```

I would create a PR for that, but I don't have a dev-environment currently up and running.

**Comment by kingsleyadam** [comment]
@derjoerg , can you test this branch to ensure it works for you? `u/kingsleyadam/addCheckForFunction`

**Comment by derjoerg** [comment]
@kingsleyadam This is working for me
