### ISSUE TITLE
Extend DimmingActuator and SwitchActuator with "forced" possibility

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#95]
The device-classes `DimmingActuator` and `SwitchActuator` have the input-datapoint `AL_FORCED` and the output-datapoint `AL_INFO_FORCE`. This is used within the F@H ecosystem to lock a device from being altered.

Unfortunately HA don't support read-only devices, so my plan would be to list the state of the `force` as a state attribute in HA and implement a service to set/unset it. I had a short discussion with other developers on discord and some of them proposed to set the device-availability to `UNKNOWN`. But I don't think this is right. The device is still there and has a state. Exposing the status as a state attribute would give the end-user at least the possibility to react on it in the dashboard (e.g. showing a lock, unset click-action, ...)

This is already done for the `CoverActuator` (`set_forced_position`).

I need to make some tests, but it looks like the possibile values are (None, forced-on and forced-off).

**Comment by derjoerg** [comment]
My private usecase for that:
I have a hallway-light, which is only controlled by a MovementDetector and after 15 seconds it automatically turns off. It can be, that I am doing something without much motion in the hallway, so I have a switch (see #93) through which the light is forced to be on until I turn off the switch.
Knowing the status in HA would give me the possibility to react on the fact, that someone set the light to forced-on and later we leave the house (after a few minutes normally all lights would go off), but as this light is set to forced-on, it can't be turned off by HA. So I can send a notification to a user, when leaving the house, that a light is set to forced-on.

Hopefully this is understandable 😃

**Comment by kingsleyadam** [comment]
Couldn't this be exposed as a new sensor instead of an attribute? You can provide the list of possible options to Home Assistant and the state would reflect one of those options.

**Comment by derjoerg** [comment]
> Couldn't this be exposed as a new sensor instead of an attribute? You can provide the list of possible options to Home Assistant and the state would reflect one of those options.

You mean: Exposing as a sensor, but changing the state through a service (or action) would still be valid?

**Comment by kingsleyadam** [comment]
If you also want to update the state you might want to consider a (Select)[https://developers.home-assistant.io/docs/core/entity/select] entity.

**Comment by kingsleyadam** [comment]
And to confirm, this isn't a boolean state is it? Where it could be implemented as a [Switch](https://developers.home-assistant.io/docs/core/entity/switch)?

**Comment by derjoerg** [comment]
> And to confirm, this isn't a boolean state is it? Where it could be implemented as a [Switch](https://developers.home-assistant.io/docs/core/entity/switch)?

I can confirm it for CoverActuator, where it can be three different states (None, forced-up, forced-down).
As written above, I need to do some tests, how it looks like for SwitchActuators and DimmingActuators, but for now I think there are also three states (None, forced-on, forced-down). So not a switch, it needs to be a select.
